### ISSUE TITLE
Moon return

### ISSUE THREAD

**Issue by bespezzano** [schlosrat/FlightPlan#31] opened 2023-10-31 02:42 UTC
Hey, I'm new to this mod so maybe I'm just doing something wrong.
I'm on orbit around Minmus and trying the Return From Moon option just puts me in an orbit around Kerbol

![image](https://github.com/schlosrat/FlightPlan/assets/24845837/f9dc39c0-aa4b-42bd-b306-0776b27f962e)

**Comment by schlosrat** [comment] 2023-10-31 02:48
Thanks for calling this to my attention. I'll take a look and see if I can replicate it so we can sort out what might be going on.

What's your starting orbit at Minimus? Ap, Pe, Inc should suffice.

Looks like you're asking to get to an orbit that will bring you within 30 km of Kerbin. Have you tried any other values? If so, what results did those give you?

**Comment by bespezzano** [comment] 2023-10-31 03:10
![image](https://github.com/schlosrat/FlightPlan/assets/24845837/b45c2356-2d10-414f-89b2-86dae238f6e1)

Tried 1 & 100K, same node as with 30K is created

**Comment by schlosrat** [comment] 2023-11-01 21:47
I've confirmed that I get a similar result starting from a similar orbit. Not sure why, but the effect is confirmed. I'll look into this.

**Comment by schlosrat** [comment] 2023-11-04 13:25
Follow-up: I've compared the code in FP to that in MJ, and this part of the code is essentially identical. I've also tried rolling back to a copy of the game I have for 0.1.4.1 with the 0.8.12 version of FP and the same issue is apparent there. I believe I can safely say this has nothing to do with the many changes from 0.1.4.1 to 0.1.5. I would need to download KSP2 0.1.3.2 to be able to test further back than that. It seems this problem has been here for a while.

As a workaround, you can use Maneuver Node Controller to simply adjust the time back and you may be able to get a suitable node that way. This is **_far_** from ideal, but it doesn't appear that I've got a quick fix for this and it's going to take a while to sort it out. I know that at one point this _was_ working reliably, so I just need to sort out what's changed since then.

**Comment by schlosrat** [comment] 2024-02-06 00:20
I'm closing this issue as I believe it's related to a larger issue I'm documenting in [Issue 49](https://github.com/schlosrat/FlightPlan/issues/49) along with notes about workarounds that may help in the meantime.

**Closed by schlosrat** 2024-02-06 00:20 UTC
